### ISSUE TITLE
ozfed logo missing

### ISSUE THREAD

**Issue by Conal-Tuohy** [Conal-Tuohy/xtf#5]
page http://adc.library.usyd.edu.au/index.jsp?database=ozfed&page=home refers to missing image http://setis.library.usyd.edu.au/fed/cfed_logo.gif

**Comment by ghost** [comment]
Hi Conal,

The correct URL is http://setis.library.usyd.edu.au/oztexts/images/cfed_logo.gif

Cheers,
Gary
